#!/bin/bash

set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

usage() {
  echo "Usage: $0 <markdown file>" 1>&2
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi

file="$1"
input_dir=$(realpath "$(dirname "$file")")

tmp=$(mktemp -d /tmp/uw-letterhead-XXXXXXXXXX)
pandoc "$file" -o "$tmp/body.tex"
pushd "$tmp" 1>/dev/null
for template_file in uw-logo.pdf midtilde.sty uw-cs-letterhead.cls; do
  cp "$DIR/$template_file" "$tmp/"
done

filebase=$(basename "$file")
filebase=${filebase%.*}
cat "$DIR/_preamble.tex" "$tmp/body.tex" "$DIR/_postamble.tex" > "$tmp/$filebase.tex"
~/sw/latexrun/latexrun "$filebase.tex"
cp "$tmp/$filebase.pdf" "$input_dir/"
popd 1>/dev/null
rm -r "$tmp"
