#!/bin/bash

set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

usage() {
  echo "Usage: $0 <markdown file>" 1>&2
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
  --help | -help | -h)
    usage
    exit 0
    ;;
  -*)
    usage
    exit 1
    ;;
  *)
    break
    ;;
  esac
done

file="$1"
input_dir=$(realpath "$(dirname "$file")")

tmp=$(mktemp -d /tmp/uw-letterhead-XXXXXXXXXX)
pandoc "$file" -o "$tmp/body.tex"
for template_file in uw-logo.pdf midtilde.sty uw-cs-letterhead.cls; do
  cp "$DIR/$template_file" "$tmp/"
done

filebase=$(basename "$file")
filebase=${filebase%.*}
cat "$DIR/_preamble.tex" "$tmp/body.tex" "$DIR/_postamble.tex" > "$tmp/$filebase.tex"
pushd "$tmp" 1>/dev/null
~/sw/latexrun/latexrun "$filebase.tex"
popd 1>/dev/null
cp "$tmp/$filebase.pdf" "$input_dir/"
rm -r "$tmp"
